### PR TITLE
Complete now returns the mouse click position relative to the contain…

### PR DESCRIPTION
**Pull request by finger563**
…er position.

For #89

### CODE REVIEW

**Comment by maxkfranz** [comment]
Published as 2.15

**Comment by finger563** [comment]
@maxkfranz does the newest version not support this anymore?

**Comment by maxkfranz** [comment]
You now get the full event: 

ehcomplete : when the edge creation gesture is successfully completed
(event, sourceNode, targetNode, addedEles)
event.position : cursor/finger position

**Comment by finger563** [comment]
Thanks! :)

**Pull request merged**
