### PR TITLE
Stack order fix providing an option to set z-index of edgehandles canvas.

### PR DESCRIPTION
**Pull request by RandallGit**
The hard-coded z-index of 999 set on the edgehandles <canvas> may cause layout issues with other UI elements and their events. Now a user can set the z-index by changing the options "stackOrder" to their desired numeric value.

### CODE REVIEW

**Comment by maxkfranz** [comment]
@RandallGit Cool, but would it be possible to maintain the two-space indentation?  Thanks!

**Comment by RandallGit** [comment]
Oh shit, my bad. I should have noticed. Untabified to two-space indent and updated. Thanks again!

**Comment by maxkfranz** [comment]
It looks like it didn't take for some reason.  I'll just merge this in and run js-beautify on it.  Thanks

**Comment by RandallGit** [comment]
Thank you and again sorry for the inconvenience.

**Pull request merged**
