### PR TITLE
init handler without jquery

### PR DESCRIPTION
**Pull request by tongbin**
for issue #40 after @maxkfranz code review, as this issue says, I need a version without jQuery, please review it as it's useful. Thanks.

### CODE REVIEW

**Comment by maxkfranz** [comment]
It looks like it's mostly working.  It works with the default options, but more complex cases break. For example, `toggleOffOnLeave: true` breaks after you make a few edges -- the edge UI disappears and there's an error in the console.

I think it's because there are small details missing in your jQuery replacement for events:

(1) `.on()` etc don't support multiple events in one call

(2) `.one()` will not work with `.off()`, because the ref sent to off doesn't match.  It probably needs something like `listener.handler` that can be read in `.off()`

(3) `handler` should be removed in `.one()`, not `listener`

(4) Misc : Each function probably shouldn't use refs to `d`, as that could potentially create memory leaks.  Probably better to use `this[0]`

**Comment by tongbin** [comment]
I've make some changes as for your advices. But I am not sure about the memory leak you mentioned here, it will be great you could explain more. Thanks quite a lot for your code review again, it helps a lot.

**Comment by maxkfranz** [comment]
@tongbin I haven't had a chance to run it, but I did take a look at the code.  It looks good.  There's just one minor thing with `.one()` I noticed:  If any of the events passed to `.one()` is emitted, then all of the events must be unbound.  Right now, it's just the event that was emitted that is removed.

As for the memory leak, I'm not sure if it happens in this particular case or not.  Generally, it's better to use `this` if it's easy instead of a reference from an upper function scope.  References from upper scopes -- especially w.r.t. listeners -- can be held by the JS engine.  In the following article, it's case 4: https://auth0.com/blog/four-types-of-leaks-in-your-javascript-code-and-how-to-get-rid-of-them/

**Comment by tongbin** [comment]
@maxkfranz  According to jQuery's document for the ```.one()``` function:

If the first argument contains more than one space-separated event types, the event handler is called once for each event type.

Though I could change it anyway, since it's maintained by us now.

For the memory leak, I've read through of it, it's quite helpful. Thanks again.

**Comment by maxkfranz** [comment]
You're right about `.one()` re. removing all handlers.  I confused it with [`.once()`](http://js.cytoscape.org/#eles.once)

**Comment by tongbin** [comment]
That's fine, please let me know if there is any other problems. Or it's ok to accept this pull request?

**Comment by maxkfranz** [comment]
I tried running it, and it looks like it's working great!

Merged and released as 2.6.0

Thanks

**Comment by tongbin** [comment]
Thanks a lot, very glad to do something for this project.

**Pull request merged**
