### PR TITLE
Add support for having an icon on edge handle

### PR DESCRIPTION
**Pull request by buffpojken**
This PR adds an option for passing an icon to be rendered on the edge handle.

### CODE REVIEW

**Comment by maxkfranz** [comment]
I tried this:

```js
var img = new Image();
img.src = '../cytoscape.js/debug/images/gnu.svg';
img.width = 10;
img.height = 10;


cy.edgehandles({
  // options go here

  handleIcon: img
});
```

It works great!

screen shot 2016-08-26 at 4 18 23 pm 3

**Comment by maxkfranz** [comment]
Merged and published as 2.5.0

**Comment by maxkfranz** [comment]
@buffpojken Thanks for your pull request!

**Comment by finger563** [comment]
@maxkfranz is this feature no longer supported? I find no references to `handleIcon` in the latest code when searching on github

**Comment by maxkfranz** [comment]
The handle is a node.  You can style it however you like in the stylesheet.  You can use multiple bg images, if you want.

**Comment by finger563** [comment]
ah cool - thanks!

**Pull request merged**
