### PR TITLE
Migrated to es6 and implemented multi handles functionality

### PR DESCRIPTION
**Pull request by dwagin**

### CODE REVIEW

**Comment by maxkfranz** [comment]
Please describe what the purpose of this PR is exactly.  It's not clear to me how this relates to https://github.com/cytoscape/cytoscape.js-edgehandles/issues/113

**Comment by dwagin** [comment]
The problem is described in #113 is related to a double call edgeType() on edge preview and on complete.

This merge request also clears graph before complete event.

**Comment by dwagin** [comment]
Hello Max Franz, first of all I want to thank you for your work. I use your project. In our opinion, we have made changes that may be useful to the community:

- Added multi handle functionality
- Project migrated to ES6 syntax

**Comment by maxkfranz** [comment]
I think you should be able to create multiple instances of the extension to create multiple handles.

**Comment by dwagin** [comment]
Thanks for the answer.
Unfortunately, I don't understand what you mean.
Could you please explain it in details.

**Pull request closed without merging**
