### PR TITLE
Allow users to change position of node handle

### PR DESCRIPTION
**Pull request by lszanto**
Adds option of handlePosition so that the handle can be moved to a different location.

Examples:
```
handlePosition: 'middle top'
handlePosition: 'middle middle'
handlePosition: 'left bottom'
handlePosition: 'right top
```

### CODE REVIEW

**Comment by maxkfranz** [comment]
@lszanto I tried this, and it worked well for `middle middle` and `middle bottom`, but it broke on `right top`.

**Comment by lszanto** [comment]
Oh really? I thought I tested them all, I'll take a look later today.

**Comment by lszanto** [comment]
@maxkfranz forgot to add the width variable so it wasn't calculating left/right properly. Should be all working now.

**Comment by maxkfranz** [comment]
Thanks

**Pull request merged**
